spring:
  application:
    name: config-server
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/InspireCampTeam3/Config.git
          search-paths:
            - article
            - auth
            - board
            - eureka
            - gateway
            - interest

server:
  port: 8071


encrypt:
  key: WeAreTestOurProjectSoHappyUmmReally

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

